version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: moneyprocessing
      POSTGRES_USER: crpostgres
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: dev-net